from __future__ import annotations

import math

import MARL_mav_carry_ext.tasks.managerbased.mdp_llc as mdp

import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import ContactSensorCfg
from isaaclab.utils import configclass
from isaaclab.utils.noise import AdditiveGaussianNoiseCfg as Gnoise

from MARL_mav_carry_ext.assets import FLYCRANE_CFG  # isort:skip

# Define the scene configuration


@configclass
class CarryingSceneCfg(InteractiveSceneCfg):
    """Configuration for multi-drone lifting system"""

    # Ground-plane
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # Lights
    distant_light = AssetBaseCfg(
        prim_path="/World/Light", spawn=sim_utils.DistantLightCfg(intensity=3000.0, color=(0.75, 0.75, 0.75))
    )

    # Drones
    robot: ArticulationCfg = FLYCRANE_CFG.replace(prim_path="{ENV_REGEX_NS}/flycrane")
    robot.spawn.activate_contact_sensors = True

    contact_forces = ContactSensorCfg(
        prim_path="{ENV_REGEX_NS}/flycrane/.*", update_period=0.0, history_length=3, debug_vis=False
    )


# MDP settings


@configclass
class CommandsCfg:
    """Commands for the hovering task"""

    pose_command = mdp.UniformPoseCommandGlobalCfg(
        asset_name="robot",
        body_name="load_odometry_sensor_link",
        resampling_time_range=(20, 20),  # out of range of max episode length for now
        debug_vis=True,
        ranges=mdp.UniformPoseCommandGlobalCfg.Ranges(
            pos_x=(-2.0, 2.0),
            pos_y=(-2.0, 2.0),
            pos_z=(0.5, 2.5),
            roll=(-math.pi/4, math.pi/4),
            pitch=(-math.pi/4, math.pi/4),
            yaw=(-math.pi, math.pi),
        ),
    )


@configclass
class ActionsCfg:
    """Actions for the hovering task.

    The ActionTerm is responsible for processing the actions and applying them to the robot,
    based on the waypoint given that will later be a trajectory generated by the policy."""

    low_level_action: mdp.LowLevelActionCfg = mdp.LowLevelActionCfg(
        asset_name="robot", body_name="Falcon.*rotor_.*", debug_vis=False, control_mode = 'ACCBR',
    )


@configclass
class ObservationsCfg:
    """Observations for the hovering task."""

    @configclass
    class PolicyCfg(ObsGroup):
        """Observation terms for the policy."""

        # payload and drone states
        payload_position = ObsTerm(func=mdp.payload_position, noise=Gnoise(std=0.003))
        payload_orientation = ObsTerm(func=mdp.payload_orientation, noise=Gnoise(std=0.01))
        payload_linear_velocities = ObsTerm(func=mdp.payload_linear_velocities, noise=Gnoise(std=0.01))
        payload_angular_velocities = ObsTerm(func=mdp.payload_angular_velocities, noise=Gnoise(std=0.02))

        drone_positions = ObsTerm(func=mdp.drone_positions, noise=Gnoise(std=0.003))
        drone_orientations = ObsTerm(func=mdp.drone_orientations, noise=Gnoise(std=0.01))
        drone_linear_velocities = ObsTerm(func=mdp.drone_linear_velocities, noise=Gnoise(std=0.01))
        drone_angular_velocities = ObsTerm(func=mdp.drone_angular_velocities, noise=Gnoise(std=0.02))

        # goal error terms
        payload_positional_error = ObsTerm(func=mdp.payload_positional_error, params={"command_name": "pose_command"}, noise=Gnoise(std=0.003))
        payload_orientation_error = ObsTerm(func=mdp.payload_orientation_error, params={"command_name": "pose_command"}, noise=Gnoise(std=0.01))

        # action terms
        previous_action = ObsTerm(func=mdp.previous_action, noise=Gnoise(std=0.01))

        def __post_init__(self):
            self.enable_corruption = False  # for adding noise to the observations
            self.concatenate_terms = True

    # Observation group
    policy: PolicyCfg = PolicyCfg()


@configclass
class EventCfg:
    """Events for the hovering task.

    Resetting states on resets, disturbances, etc.
    """

    reset_base = EventTerm(
        func=mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {
                "x": (-1.0, 1.0),
                "y": (-1.0, 1.0),
                "z": (0.5, 1.5),
                "roll": (-0, 0),
                "pitch": (-0, 0),
                "yaw": (-math.pi, math.pi),
            },
            "velocity_range": {
                "x": (-0.0, 0.0),
                "y": (-0.0, 0.0),
                "z": (-0.0, 0.0),
                "roll": (-0.0, 0.0),
                "pitch": (-0.0, 0.0),
                "yaw": (-0.0, 0.0),
            },
        },
    )

    # reset_base = EventTerm(
    #     func=mdp.reset_root_state_uniform,
    #     mode="reset",
    #     params={
    #         "pose_range": {
    #             "x": (0.0, 0.0),
    #             "y": (0.0, 0.0),
    #             "z": (0.0, 1.5),
    #             "roll": (-0, 0),
    #             "pitch": (-0, 0),
    #             "yaw": (0.0, 0.0),
    #         },
    #         "velocity_range": {
    #             "x": (-0.0, 0.0),
    #             "y": (-0.0, 0.0),
    #             "z": (-0.0, 0.0),
    #             "roll": (-0.0, 0.0),
    #             "pitch": (-0.0, 0.0),
    #             "yaw": (-0.0, 0.0),
    #         },
    #     },
    # )

    base_external_force_torque = EventTerm(
        func=mdp.apply_external_force_torque,
        mode="reset",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=".*"),
            "force_range": (0.0, 0.0),
            "torque_range": (-0.0, 0.0),
        },
    )

    reset_robot_joints = EventTerm(
        func=mdp.reset_joints_by_scale,
        mode="reset",
        params={
            "position_range": (0.0, 0.0),
            "velocity_range": (0.0, 0.0),
        },
    )


@configclass
class RewardsCfg:
    """Rewards for the hovering task."""

    pos_reward = RewTerm(
        func=mdp.track_payload_pos_command,
        weight=1.5,
        params={"command_name": "pose_command"},
    )

    ori_reward = RewTerm(
        func=mdp.track_payload_orientation_command,
        weight=1.5,
        params={"command_name": "pose_command", "debug_vis": False},
    )

    force_penalty = RewTerm(
        func=mdp.action_penalty_force,
        weight=0.5,
    )

    action_smoothness = RewTerm(
        func=mdp.action_smoothness_ACCBR_reward,
        weight=0.5,
    )

    downwash_reward = RewTerm(
        func=mdp.downwash_reward,
        weight=0.5,
    )


@configclass
class TerminationsCfg:
    """Terminal conditions for the hovering task.

    When the payload reaches a certain height, etc."""

    # end when sim times out
    time_out = DoneTerm(func=mdp.time_out, time_out=True)

    illegal_contact = DoneTerm(
        func=mdp.illegal_contact,
        params={"sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*"), "threshold": 0.1},
    )

    # end when falcons crash
    falcon_fly_low = DoneTerm(func=mdp.falcon_fly_low, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.1})
    payload_fly_low = DoneTerm(
        func=mdp.payload_fly_low, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.1}
    )

    angle_drones_cable = DoneTerm(
        func=mdp.cable_angle_drones_cos, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.05}
    )
    angle_load_cable = DoneTerm(
        func=mdp.cable_angle_payload_cos, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.0}
    )

    cables_collide = DoneTerm(
        func=mdp.cable_collision, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.2, "num_points": 10}
    )

    drones_collide = DoneTerm(func=mdp.drone_collision, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.2})

    bounding_box = DoneTerm(func=mdp.bounding_box, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 5.0})

@configclass
class CurriculumCfg:
    """Curriculum for the hovering task."""

    pass


@configclass
class HoverEnvCfg_llc(ManagerBasedRLEnvCfg):
    """Configuration for the hovering task."""

    scene: CarryingSceneCfg = CarryingSceneCfg(num_envs=1, env_spacing=4.0)
    commands: CommandsCfg = CommandsCfg()
    actions: ActionsCfg = ActionsCfg()
    observations: ObservationsCfg = ObservationsCfg()
    events: EventCfg = EventCfg()
    rewards: RewardsCfg = RewardsCfg()
    terminations: TerminationsCfg = TerminationsCfg()
    curriculum: CurriculumCfg = CurriculumCfg()

    def __post_init__(self):
        """Post initialization."""
        # general settings
        self.decimation = 3
        self.episode_length_s = 20.0
        # simulation settings
        self.sim.dt = 0.0033333333333333335
        self.sim.render_interval = self.decimation
        self.sim.disable_contact_processing = True
        self.sim.gravity = (0.0, 0.0, -9.8066)
